services:
  ticket-sales-api:
    build:
      context: .  # Diretório atual (bilheteria-api)
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8082"  # Porta para ticket-sales-api
    networks:
      - dac-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-bilheteria:5432/ticketOffice
      SPRING_DATASOURCE_USERNAME: ticketOffice
      SPRING_DATASOURCE_PASSWORD: ticketOffice
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin123
    restart: always

  postgres:
    image: postgres
    container_name: postgres-db-bilheteria
    environment:
      - POSTGRES_PASSWORD=ticketOffice
      - POSTGRES_USER=ticketOffice
      - POSTGRES_DB=ticketOffice
    networks:
      - dac-network
    ports:
      - "5433:5432"
    restart: always

networks:
  dac-network:
    name: dac-network
    driver: bridge